### PR TITLE
Finished article.

### PR DESCRIPTION
**Pull request by courtneybroderick**

### CODE REVIEW

**Comment by jlcohoon** [comment]
@courtneybroderick, before I merge these, can you change the name of your files back so that they reflect the name of the article you're coding? For instance, your file named article1.ttl should be PMC3064792.ttl

**Comment by courtneybroderick** [comment]
Just committed the renamed files.  :)

Courtney Broderick
________________________________________

**Comment by jlcohoon** [comment]
@courtneybroderick, thanks for doing that! It looks good.

I'm actually going to close this pull request because of the number of files in it that you did not actually modify yourself. You can open a new pull request as soon as you like. When you do that, you should see that far fewer files (dozens, maybe, but not 2000) will be included. If you have trouble, let me know. You'll always be able to see this pull request and our conversation by visiting the pull requests tab and clicking on "closed."

**Comment by courtneybroderick** [comment]
Awesome!  Thanks Hannah!


________________________________________

**Pull request closed without merging**
