### PR TITLE
Coding all previous articles

### PR DESCRIPTION
**Pull request by evelynkue**

### CODE REVIEW

**Comment by jlcohoon** [comment]
@evelynkue, can you go through your files and be sure that if you have coded an in-text mention it is listed in the article block? i noticed in PMC2731890 and PMC3040438 that you have a bunch of mentions not listed at the top. see the example file here for what this should look like: https://howisonlab.github.io/softcite-dataset/practice-files/example-PMC2529246.ttl

there might be more files than those two with those problems—please double check the rest of the files yourself.

**Comment by evelynkue** [comment]
Is this not what my files look like?

**Comment by jlcohoon** [comment]
@evelynkue, no it isn't (at least not always). I saw two files that you've coded several mentions for, but the article block only says that there's one. The article block works as a sort of table of contents, listing out all of the in-text mentions that you code. So, like in the example file I linked to, if you have four in-text mention blocks then you need to have four in-text mentions named in the article block at the top. I saw two files so far that need the rest of their mentions listed (PMC2731890 and PMC3040438), but didn't look through all of your files to see how many of them need attention. Can you please look through all of them and add the ITMs to the article block as necessary? Also, if this explanation isn't making sense, we can just meet really quickly some time this week and I can show you in person—whatever works for you.

**Comment by evelynkue** [comment]
Sorry, I’m still kind of confused by this. Could we meet next week?

**Comment by jlcohoon** [comment]
Definitely! How's Monday afternoon look for you?

**Comment by evelynkue** [comment]
I’m free between 1 and 3! It would probably be easier if I met you around 1

**Comment by jlcohoon** [comment]
@evelynkue, I'm going to close this PR because it includes a bunch of files that you didn't actually edit yourself. You'll still be able to refer to it at any time by clicking on "Closed" here: https://github.com/howisonlab/softcite-dataset/pulls. 

When you've finished checking out all the files to be sure the ITMs are named correctly in the article block, just open another PR. You should end up with only having a dozen or so modified files rather than thousands. If, when you do that, you have any trouble, just shoot me a message. I'm happy to help!

**Pull request closed without merging**
