### PR TITLE
coded a couple of articles

### PR DESCRIPTION
**Pull request by sehreenali**

### CODE REVIEW

**Comment by jameshowison** [comment]
Hi @sehreenali I took a quick look.   If you say it is not software then you don't have to do the rest of the codes. In this case, though, BLASTN is software (it implements an algorithm), so you should change the mention_type, add, commit, push and the pull request will update.

**Comment by jameshowison** [comment]
@sehreenali did you see my comment above?  A few fixes needed to the files before I can merge this (not syntactical so the tests aren't catching the issue).

**Comment by sehreenali** [comment]
Yes, I will go ahead and fix it by today and recommit! In the future, if it
isn't a software I can go ahead and delete everything after saying it is
algorithm, correct?

**Comment by jameshowison** [comment]
Correct :)  You can just make changes, then add and commit and they'll come
into the pull request.

**Pull request closed without merging**
