### PR TITLE
new files added

### PR DESCRIPTION
**Pull request by JaskiratSingh23**

### CODE REVIEW

**Comment by jameshowison** [comment]
A couple of syntax errors need to be fixed here, @JaskiratSingh23 .  Could you run the tests, fix the rrors, add, commit, and push?

/home/travis/build/howisonlab/softcite-dataset/code/test_rdf_syntax.py:14: Failed: BadSyntax: Use python3 code/parseTurtle.py -f data/individuals-jaskiratsingh23/jaskiratsingh23-PMC3246293.ttl
/home/travis/build/howisonlab/softcite-dataset/code/test_rdf_syntax.py:14: Failed: BadSyntax: Use python3 code/parseTurtle.py -f data/individuals-jaskiratsingh23/jaskiratsingh23-PMC4131081.ttl
/home/travis/build/howisonlab/softcite-dataset/code/test_rdf_syntax.py:14: Failed: BadSyntax: Use python3 code/parseTurtle.py -f data/individuals-jaskiratsingh23/jaskiratsingh23-PMC4257079.ttl
/home/travis/build/howisonlab/softcite-dataset/code/test_rdf_syntax.py:14: Failed: BadSyntax: Use python3 code/parseTurtle.py -f data/individuals-jaskiratsingh23/jaskiratsingh23-PMC4812504.ttl

**Comment by JaskiratSingh23** [comment]
Hi Dr Howison,

Thank you so much for letting notifying me. I'll do it right away and let
you know.

Best,
Jaskirat Singh

**Comment by JaskiratSingh23** [comment]
Hi Dr Howison,

Can you please help me with this thing.The pytest command shows an error in
the file "PMC4257079.TTL" but I cannot find any error on the specified
lines.
[image: Inline image 1]

Best,
Jaskirat Singh

**Comment by jameshowison** [comment]
This is what you are seeing, right?

```
jaskiratsingh23@howisonlab:~/softcite-dataset$ python3 code/parseTurtle.py -f data/individuals-jaskiratsingh23/jaskiratsingh23-PMC4257079.ttl
Traceback (most recent call last):
  File "code/parseTurtle.py", line 125, in <module>
    main(sys.argv[1:])
  File "code/parseTurtle.py", line 120, in main
    validate_file(a)
  File "code/parseTurtle.py", line 46, in validate_file
    check_selections_in_body(file_graph)
  File "code/parseTurtle.py", line 71, in check_selections_in_body
    raise Exception("Did not find {}".format(sel))
Exception: Did not find https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4257079_JS01
```
Those are line numbers from the python script, not the file. It's a validation check that all the mentions you declare at the top of the file are there.  Looking at the file I think there is an extra colon (:) at the end of pmcid:PMC4257079_JS01:

Try removing that colon?

**Comment by JaskiratSingh23** [comment]
That helps. Thankyou again.

**Comment by JaskiratSingh23** [comment]
Hi Dr Howison,

I have made all the corrections and also made the add, commit and push commands. However, there are still like 5 pending files that I need to code. I will try to get that done at the earliest. 

Best,
Jaskirat Singh

**Pull request merged**
