### PR TITLE
New coded articles

### PR DESCRIPTION
**Pull request by evelynkue**

### CODE REVIEW

**Comment by jameshowison** [comment]
Evelyn somehow the data/softcite_assignments.csv file has ended up in your pull request. Can you remove that?  Probably easiest to do:

git checkout data/softcite_assignments.csv
git add data/softcite_assignments.csv
git commit -m "removed file"
git push

that will reset the file to what it was.  Try not to git add files outside your individuals folder.

**Comment by evelynkue** [comment]
I tried doing what you said to do, but I keep getting the message in the
screenshot.

**Comment by jameshowison** [comment]
Hmmm, I don't see a screenshot.  Could you either copy and paste the error or email it to me?

**Comment by evelynkue** [comment]
screen shot 2017-11-12 at 12 17 13 am

**Comment by jameshowison** [comment]
I run the second command that is in that screenshot:

git config --global push.default simple

Then when I type `git push` I don't have to type `git push origin master`

**Comment by jameshowison** [comment]
the data/softcite_assignments.csv file is still in this pull request, the goal is to remove it.
Try 
git checkout -- data/softcite_assignments.csv
(ie adding the -- for git checkout).

**Comment by evelynkue** [comment]
Okay, I just tried that code. Hopefully the file is out of my pull request now.

**Pull request merged**
