### PR TITLE
revamping initial agreement script

### PR DESCRIPTION
**Pull request by caifand**
Please help check line 308-309 (in RStudio, when building the tibble `matching` from line 300)
```
filter(start_val.x <= end_val.y, 
          start_val.y <= end_val.x) %>% 
```
Here R cannot do such comparison between two lists within a tibble.

Cannot proceed so cannot verify the percentage agreement results.

Thanks!

### CODE REVIEW

**Comment by jameshowison** [comment]
Getting this running locally again, standby!

**Comment by jameshowison** [comment]
I don't see this error when running the script now in Master.  I did have to update some install stuff to make this work via Docker, though, perhaps some versioning issues.  OTOH I did load in your branch and I do see some errors.  But I'm not sure what other changes were made (I could look at the diffs but I'm out of time this morning).  So could you start with the new version on master and use the Docker environment to run it?  Then brings changes over from your branch (basically sync with master).

To run using the Docker environment you need the `softcite-dataset` repo and the `softcite-pdf-files` repo both inside a higher folder (ie make them folder siblings), then run `docker-compose up` which will run rstudio on http://localhost:8789.  Then on the R console you need to run dwapi::configure with your API key.  After that the script should run; for me it runs through to the end, creating figures etc.  Can you check?

**Comment by caifand** [comment]
@jameshowison Sounds great. Have you already put a .yml file in the repo for docker-composing? I think it's the precondition for me to run the docker image? (It's possible that I am wrong :)

**Comment by jameshowison** [comment]
Good point.  Done now.  Note that the softcite-pdf-files need to be in a
sibling of the softcite-dataset folder.  You can use a symbolic link there,
probably.  Or adjust the path in the docker-compose.yml file.

**Comment by caifand** [comment]
@jameshowison Appreciated. But, sorry, my questions might be a bit misleading. Perhaps we actually need a Dockerfile in the repo instead of a docker-compose.yml?
When I am running `docker-compose up` I am getting this:
```
D@DESKTOP-36ENMK6 MINGW64 ~/Documents/Academics/2-Projects/HowisonLab/softcite-on-Server/softcite-dataset (master)
$ docker-compose up
Building softcite
ERROR: Cannot locate specified Dockerfile: Dockerfile
```
And I am not pretty sure if you are applying a multi-container scenario here?

Thanks for your help again! Or maybe you can just push your recent changes into the repo first if that's quicker?

**Comment by jameshowison** [comment]
My fault, now Dockerfile is there too.  I did test this, but forgot to run
docker-compose build first (so docker-compose up found the existing
container in my Docker setup).

It's not a multiple container situation but I always forget the
commandline arguments for mounting the directories, and docker-compose
allows me to specify them in the docker-compose.yml file.

Hope it works now,
James

**Comment by caifand** [comment]
@jameshowison I can compose up now but are you sure that I do not need a username?

Or I misunderstand any step for running the application in the container?

**Comment by caifand** [comment]
@jameshowison Ah, got in. No worries now. Thanks!

**Comment by caifand** [comment]
The original script included negatively coded econ articles. Now all taken away.

**Pull request merged**
