### PR TITLE
Coded articles for last week

### PR DESCRIPTION
**Pull request by yashkar**

### CODE REVIEW

**Comment by jlcohoon** [comment]
@yashkar, can you double check your files to be sure that if you say there is a mention, you've coded it? I noticed in a couple of your files that you name a mention but don't refer to it again later. see PMC3948830 for an example of the issue.

**Comment by jlcohoon** [comment]
@yashkar, I'm still seeing that you have named some in text mentions in the article block when you didn't actually code any (e.g. in yashkar-PMC3936631.ttl and yashkar-PMC4932304.ttl) and that you didn't name some when you did code more than 1 (e.g. yashkar-PMC4225645.ttl). Can you please check all of your data files and be sure that the article block names all (and only) the in text mentions that you coded? If you're confused about what I mean, let's meet for 20 minutes some time this week to go over it.

Please leave a comment here to let me know if you've fixed the issue or would like to meet.

**Comment by yashkar** [comment]
@jlcohoon I misunderstood what in text mention blocks were and therefore filled it in every file irrespective of whether it contained the mentions or no. I ll fix them and commit them again. I am extremely sorry for the issue. I am still not sure about what's missing in PMC4225645.ttl. I ll meet you on Friday itself and get that part cleared. Once again, apologies for all the mess.

**Comment by jameshowison** [comment]
This was from before re-forking, if you haven't re-forked contact Hannah to get set up again.

**Pull request closed without merging**
